//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class LibrosLectores : IEquatable<LibrosLectores>
    {
        public LibrosLectores(string isbn, int nCarnet, DateTime? fechaPrestamo, DateTime? fechaDevolucion, Lector lectores, Libro libro)
        {
            Isbn = isbn;
            NCarnet = nCarnet;
            FechaPrestamo = fechaPrestamo;
            FechaDevolucion = fechaDevolucion;
            Lectores = lectores;
            Libro = libro;
        }

        public LibrosLectores()
        {
        }

        public LibrosLectores(string isbn, int nCarnet, DateTime? fechaPrestamo, DateTime? fechaDevolucion)
        {
            Isbn = isbn;
            NCarnet = nCarnet;
            FechaPrestamo = fechaPrestamo;
            FechaDevolucion = fechaDevolucion;
        }

        public string Isbn { get; set; }
        public int NCarnet { get; set; }
        public Nullable<System.DateTime> FechaPrestamo { get; set; }
        public Nullable<System.DateTime> FechaDevolucion { get; set; }
    
        public virtual Lector Lectores { get; set; }
        public virtual Libro Libro { get; set; }

        public override bool Equals(object obj)
        {
            return Equals(obj as LibrosLectores);
        }

        public bool Equals(LibrosLectores other)
        {
            return other != null &&
                   Isbn == other.Isbn &&
                   NCarnet == other.NCarnet;
        }

        public override int GetHashCode()
        {
            var hashCode = 1180959073;
            hashCode = hashCode * -1521134295 + EqualityComparer<string>.Default.GetHashCode(Isbn);
            hashCode = hashCode * -1521134295 + NCarnet.GetHashCode();
            return hashCode;
        }
    }
}
